# server
server:
  port: 8880
  servlet:
    context-path: /jaywu
  tomcat:
    uri-encoding: UTF-8

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jaywu?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#mp配置
mybatis-plus:
  #mapper存在resources下
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  #typeAliasesPackage: com.jaywu.modular.*.entity
  #typeEnumsPackage: com.jaywu.modular.*.entity.enums
  global-config:
    #数据库相关配置
    db-config:
      #数据库类型
      db-type: mysql
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
    #刷新mapper 调试神器
    refresh: true
    #是否允许缓存
    cache-enabled: false
    sql-parser-cache: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#Logger Config
logging:
  #可自定义日志名
  config: classpath:logback-spring.xml

wx:
  mp:
    configs:
      - appId: wx12202ff07da277bb
        secret: 30d1c7b04ea37ad6764faceb49b51108
        token: ybltestmptoken
        aesKey: Bjte9IvAxbLNse6DWQ0sdVx3zBWoLB4pQtJTKWnGKch
      - appId: wx21c22acfb6b27142
        secret: 662a21a2429be8b648af80152d998cd3
        token: 111
        aesKey: 222

# 是否启用“调试”模式，开启后会打印很多日志
#debug: false